import { CalendarDays, Heart, MapPin, Star, Users, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "../services/api";
import { useAuth } from "../context/AuthContext";
import toast from "react-hot-toast";
import Loading from "../components/Loading";

export default function ListingDetails(){
  const {id}=useParams(); const {user,setUser}=useAuth(); const [listing,setListing]=useState(null); const [reviews,setReviews]=useState([]); const [form,setForm]=useState({checkIn:"",checkOut:"",guests:1}); const [review,setReview]=useState({rating:5,comment:""}); const [busy,setBusy]=useState(false);
  const load=async()=>{try{const {data}=await api.get(`/listings/${id}`);setListing(data.listing);setReviews(data.reviews);}catch(e){toast.error("Listing not found");}};
  useEffect(()=>{load()},[id]);
  if(!listing)return <Loading/>;
  const liked=user?.favorites?.some(x=>String(x?._id||x)===String(id));
  async function favorite(){if(!user)return toast.error("Login to save favorites");try{const {data}=await api.post(`/listings/${id}/favorite`);setUser(p=>({...p,favorites:data.favorites}));toast.success(data.favorited?"Saved":"Removed");}catch(e){toast.error(e.response?.data?.message||"Error")}}
  async function book(e){e.preventDefault();setBusy(true);try{await api.post("/bookings",{listingId:id,...form});toast.success("Booking confirmed");setForm({checkIn:"",checkOut:"",guests:1});}catch(e){toast.error(e.response?.data?.message||"Booking failed")}finally{setBusy(false)}}
  async function addReview(e){e.preventDefault();try{const {data}=await api.post(`/reviews/listing/${id}`,review);setReviews(r=>[data.review,...r]);setReview({rating:5,comment:""});load();toast.success("Review added");}catch(e){toast.error(e.response?.data?.message||"Could not add review")}}
  async function deleteReview(rid){try{await api.delete(`/reviews/${rid}`);setReviews(r=>r.filter(x=>x._id!==rid));load();}catch(e){toast.error("Could not delete review")}}
  return <section className="container details"><Link to="/" className="back">← Back to explore</Link><div className="gallery">{listing.images?.map((img,i)=><img key={i} src={img.url} alt={`${listing.title} ${i+1}`}/>)}</div><div className="details-grid"><article><div className="row-between"><div><span className="eyebrow">{listing.category}</span><h1>{listing.title}</h1><p className="muted"><MapPin size={16}/> {listing.location}, {listing.country}</p></div><button className={liked?"heart liked big":"heart big"} onClick={favorite}><Heart fill={liked?"currentColor":"none"}/></button></div><p className="description">{listing.description}</p><div className="facts"><span><Users/> Up to {listing.maxGuests} guests</span><span><Star fill="currentColor"/> {listing.ratingAverage?.toFixed?.(1)||"New"} ({listing.reviewCount||0})</span></div><h2>Reviews</h2>{user&&<form className="review-form" onSubmit={addReview}><select value={review.rating} onChange={e=>setReview({...review,rating:e.target.value})}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select><textarea required placeholder="Share your experience..." value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})}/><button className="secondary">Add review</button></form>}{reviews.length?<div className="reviews">{reviews.map(r=><div className="review" key={r._id}><div className="row-between"><strong>{r.author?.name}</strong><span className="rating"><Star size={14} fill="currentColor"/> {r.rating}</span></div><p>{r.comment}</p>{(user&&String(user.id||user._id)===String(r.author?._id))||user?.role==="admin"?<button className="icon-button" onClick={()=>deleteReview(r._id)}><Trash2 size={15}/></button>:null}</div>)}</div>:<p className="muted">No reviews yet.</p>}</article><aside className="booking-card"><h2>₹{listing.price.toLocaleString()} <small>/ night</small></h2><form onSubmit={book}><label>Check in<input type="date" required value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></label><label>Check out<input type="date" required value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></label><label>Guests<input type="number" min="1" max={listing.maxGuests} value={form.guests} onChange={e=>setForm({...form,guests:e.target.value})}/></label><button className="primary full" disabled={busy}>{busy?"Booking...":"Reserve"}</button></form><p className="muted"><CalendarDays size={15}/> Your dates are checked for availability before confirmation.</p></aside></div></section>
}
